required = ["github.com/onsi/ginkgo/ginkgo"]

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry/bosh-utils"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.3.0"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
