---
platform: linux
image_resource:
  type: docker-image
  source: {repository: bosh/s3cli}
inputs:
- name: davcli-src
  path: bosh-davcli
- name: version-semver
outputs:
- name: out
run:
  path: bosh-davcli/ci/tasks/build.sh
params:
  GOOS: linux
  GOARCH: amd64
